name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
          date
          go build .
          mkdir output
          ./magireco
          cp index.html output/index.html
    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: index.html
        path: index.html
    - name : deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
